name: Format

on:
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: -w .
          commit_message: 'lint: run prettier from gh actions'
